update

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,1 +1,16 @@
-npm test
+#!/bin/sh
+. "$(dirname "$0")/_/husky.sh"
+
+# Запускаем тесты
+npm run test
+if [ $? -ne 0 ]; then
+  echo "Tests failed, aborting commit"
+  exit 1
+fi
+
+# Запускаем линтинг
+npm run lint
+if [ $? -ne 0 ]; then
+  echo "Linting failed, aborting commit"
+  exit 1
+fi
